-- Migration: Populate why_wrong column from why_wrong_choices data
-- Generated: 2026-01-17T20:30:34.817Z
-- Records: 90

UPDATE question_choices SET why_wrong = 'tax determination is a separate objective under tax laws, not PFRS' WHERE choice_id = 230;
UPDATE question_choices SET why_wrong = 'management performance assessment is secondary, not primary' WHERE choice_id = 231;
UPDATE question_choices SET why_wrong = 'regulatory compliance is a consequence, not the primary objective' WHERE choice_id = 232;
UPDATE question_choices SET why_wrong = 'faithful representation is about accuracy, not decision-usefulness' WHERE choice_id = 233;
UPDATE question_choices SET why_wrong = 'comparability is an enhancing characteristic, not fundamental' WHERE choice_id = 235;
UPDATE question_choices SET why_wrong = 'verifiability is also an enhancing characteristic' WHERE choice_id = 236;
UPDATE question_choices SET why_wrong = 'control, not legal ownership, is the criterion' WHERE choice_id = 238;
UPDATE question_choices SET why_wrong = 'this describes current assets only, not all assets' WHERE choice_id = 239;
UPDATE question_choices SET why_wrong = 'potential for benefits is sufficient; certainty is not required' WHERE choice_id = 240;
UPDATE question_choices SET why_wrong = 'these are all enhancing characteristics' WHERE choice_id = 241;
UPDATE question_choices SET why_wrong = 'these are all enhancing characteristics' WHERE choice_id = 242;
UPDATE question_choices SET why_wrong = 'these are all enhancing characteristics' WHERE choice_id = 244;
UPDATE question_choices SET why_wrong = 'income includes gains too' WHERE choice_id = 245;
UPDATE question_choices SET why_wrong = 'owner contributions are equity, not income' WHERE choice_id = 247;
UPDATE question_choices SET why_wrong = 'not ALL asset increases are income (e.g., borrowing increases assets but isn''t income)' WHERE choice_id = 248;
UPDATE question_choices SET why_wrong = 'original cost is irrelevant; the NEW partnership starts fresh' WHERE choice_id = 249;
UPDATE question_choices SET why_wrong = 'book value may differ from fair/agreed value' WHERE choice_id = 251;
UPDATE question_choices SET why_wrong = 'no such rule; it''s purely based on agreement' WHERE choice_id = 252;
UPDATE question_choices SET why_wrong = 'the bonus is FROM old partners, not charged to new partner' WHERE choice_id = 253;
UPDATE question_choices SET why_wrong = 'bonus method does NOT record goodwill' WHERE choice_id = 254;
UPDATE question_choices SET why_wrong = 'it''s a capital adjustment, not an expense' WHERE choice_id = 256;
UPDATE question_choices SET why_wrong = 'outside creditors have FIRST priority, not last' WHERE choice_id = 257;
UPDATE question_choices SET why_wrong = 'partners'' loans come before capital' WHERE choice_id = 258;
UPDATE question_choices SET why_wrong = 'outside creditors must be paid first' WHERE choice_id = 260;
UPDATE question_choices SET why_wrong = 'Investment in Branch is an asset but Home Office is not' WHERE choice_id = 261;
UPDATE question_choices SET why_wrong = 'neither is a liability' WHERE choice_id = 262;
UPDATE question_choices SET why_wrong = 'neither is an expense' WHERE choice_id = 264;
UPDATE question_choices SET why_wrong = 'book value ignores appreciation/depreciation' WHERE choice_id = 265;
UPDATE question_choices SET why_wrong = 'historical cost is acquiree''s cost, not current value' WHERE choice_id = 267;
UPDATE question_choices SET why_wrong = 'replacement cost is not the PFRS 3 measurement basis' WHERE choice_id = 268;
UPDATE question_choices SET why_wrong = 'auditors are not responsible for detecting ALL fraud' WHERE choice_id = 269;
UPDATE question_choices SET why_wrong = 'auditors don''t guarantee accuracy' WHERE choice_id = 271;
UPDATE question_choices SET why_wrong = 'management prepares financial statements, not auditors' WHERE choice_id = 272;
UPDATE question_choices SET why_wrong = 'oral evidence is least reliable' WHERE choice_id = 273;
UPDATE question_choices SET why_wrong = 'internal documents can be manipulated' WHERE choice_id = 274;
UPDATE question_choices SET why_wrong = 'client computations may contain errors' WHERE choice_id = 276;
UPDATE question_choices SET why_wrong = 'modified opinion is a result, not the definition of materiality' WHERE choice_id = 277;
UPDATE question_choices SET why_wrong = 'criminal prosecution is a legal matter, unrelated' WHERE choice_id = 279;
UPDATE question_choices SET why_wrong = 'there''s no fixed percentage; it depends on circumstances' WHERE choice_id = 280;
UPDATE question_choices SET why_wrong = 'six months is too short' WHERE choice_id = 281;
UPDATE question_choices SET why_wrong = 'three years is beyond the requirement' WHERE choice_id = 283;
UPDATE question_choices SET why_wrong = 'indefinite assessment is impractical' WHERE choice_id = 284;
UPDATE question_choices SET why_wrong = 'risk assessment identifies and analyzes risks' WHERE choice_id = 285;
UPDATE question_choices SET why_wrong = 'control activities are specific procedures' WHERE choice_id = 286;
UPDATE question_choices SET why_wrong = 'monitoring evaluates control effectiveness' WHERE choice_id = 288;
UPDATE question_choices SET why_wrong = 'in-kind benefits are also taxable' WHERE choice_id = 289;
UPDATE question_choices SET why_wrong = 'bank deposit is not the trigger' WHERE choice_id = 291;
UPDATE question_choices SET why_wrong = 'financial reporting differs from tax reporting' WHERE choice_id = 292;
UPDATE question_choices SET why_wrong = 'this applies to aliens and non-resident citizens' WHERE choice_id = 293;
UPDATE question_choices SET why_wrong = 'Philippine income is definitely taxable' WHERE choice_id = 294;
UPDATE question_choices SET why_wrong = 'all types of income are taxable, not just capital gains' WHERE choice_id = 296;
UPDATE question_choices SET why_wrong = 'bonuses are part of compensation, taxable' WHERE choice_id = 297;
UPDATE question_choices SET why_wrong = 'rental income is taxable' WHERE choice_id = 299;
UPDATE question_choices SET why_wrong = 'professional fees are taxable income' WHERE choice_id = 300;
UPDATE question_choices SET why_wrong = 'P2,500 exceeds the P2,000 limit, excess is taxable' WHERE choice_id = 301;
UPDATE question_choices SET why_wrong = 'there''s a specific limit' WHERE choice_id = 303;
UPDATE question_choices SET why_wrong = 'the limit is per month, not annual' WHERE choice_id = 304;
UPDATE question_choices SET why_wrong = 'bank interest is not exempt' WHERE choice_id = 305;
UPDATE question_choices SET why_wrong = 'final tax, not graduated rates' WHERE choice_id = 307;
UPDATE question_choices SET why_wrong = '20% is the correct rate for bank interest' WHERE choice_id = 308;
UPDATE question_choices SET why_wrong = 'depreciation is fixed, doesn''t change with production' WHERE choice_id = 309;
UPDATE question_choices SET why_wrong = 'supervisor salary is fixed regardless of output' WHERE choice_id = 311;
UPDATE question_choices SET why_wrong = 'insurance is a fixed cost' WHERE choice_id = 312;
UPDATE question_choices SET why_wrong = 'that would be profit, not break-even' WHERE choice_id = 313;
UPDATE question_choices SET why_wrong = 'variable and fixed costs don''t have to be equal' WHERE choice_id = 315;
UPDATE question_choices SET why_wrong = 'contribution margin covers fixed costs at break-even' WHERE choice_id = 316;
UPDATE question_choices SET why_wrong = 'fixed costs are not deducted at unit level' WHERE choice_id = 317;
UPDATE question_choices SET why_wrong = 'total cost includes fixed, which shouldn''t be per-unit allocated this way' WHERE choice_id = 319;
UPDATE question_choices SET why_wrong = 'this formula is meaningless' WHERE choice_id = 320;
UPDATE question_choices SET why_wrong = 'sunk costs are NEVER relevant' WHERE choice_id = 321;
UPDATE question_choices SET why_wrong = 'sunk costs cannot change; that describes relevant costs' WHERE choice_id = 323;
UPDATE question_choices SET why_wrong = 'opportunity cost is what you give up by choosing' WHERE choice_id = 324;
UPDATE question_choices SET why_wrong = 'this describes quantity variance, not price variance' WHERE choice_id = 325;
UPDATE question_choices SET why_wrong = 'higher price would be unfavorable' WHERE choice_id = 327;
UPDATE question_choices SET why_wrong = 'this also describes quantity variance' WHERE choice_id = 328;
UPDATE question_choices SET why_wrong = 'most contracts can be oral' WHERE choice_id = 329;
UPDATE question_choices SET why_wrong = 'notarization is for convenience, not validity' WHERE choice_id = 331;
UPDATE question_choices SET why_wrong = 'registration is not required for validity' WHERE choice_id = 332;
UPDATE question_choices SET why_wrong = 'there''s a defect in consent' WHERE choice_id = 333;
UPDATE question_choices SET why_wrong = 'it''s not void, just voidable' WHERE choice_id = 334;
UPDATE question_choices SET why_wrong = 'unenforceable is a different category' WHERE choice_id = 336;
UPDATE question_choices SET why_wrong = 'perfection creates obligations, not ownership transfer' WHERE choice_id = 337;
UPDATE question_choices SET why_wrong = 'payment is separate from delivery' WHERE choice_id = 338;
UPDATE question_choices SET why_wrong = 'registration is not required for ownership transfer in general' WHERE choice_id = 340;
UPDATE question_choices SET why_wrong = 'reinvindicatoria is to recover ownership, not about defects' WHERE choice_id = 341;
UPDATE question_choices SET why_wrong = 'publiciana is to recover possession' WHERE choice_id = 343;
UPDATE question_choices SET why_wrong = 'pauliana is creditor''s action against fraudulent transfers' WHERE choice_id = 344;
UPDATE question_choices SET why_wrong = 'checks are payable on demand, not with maturity date' WHERE choice_id = 345;
UPDATE question_choices SET why_wrong = 'stating the reason makes it conditional' WHERE choice_id = 347;
UPDATE question_choices SET why_wrong = 'collateral is not a requirement' WHERE choice_id = 348;
